export const CANVAS_CONSTANTS = {
  HANDLE_SIZE: 8,
  ROTATION_HANDLE_SIZE: 6,
  ROTATION_HANDLE_DISTANCE: 30,
  LINE_WIDTH: 1.5,
  MIN_REGION_SIZE: 10,
  MIN_CHILD_REGION_SIZE: 5,
  DASH_PATTERN: [5, 5],
} as const;

export const COLORS = {
  PRIMARY: '#3b82f6',
  CHILD: '#3b82f6',
  SELECTED: '#2563eb',
} as const;
